---
- name: Update package cache and upgrade packages
  hosts: all
  become: true

  tasks:
    - name: Upgrade all packages (Debian)
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Upgrade all packages (RedHat)
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

- name: Install and config nginx on webservers
  hosts: webservers
  become: true

  tasks:
    - name: Install nginx package
      ansible.builtin.package:
        name: nginx

    - name: Ensure nginx is started and enabled
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Create the config file for nginx
      ansible.builtin.copy:
        src: conf-files/nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: "0644"
      notify: Reload nginx

  handlers:
    - name: Reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
