all:
  hosts:
    lab1:
      ansible_host: 192.168.47.10
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/test/libvirt/private_key

  children:
    webservers:
      hosts:
        lab1:
